### ISSUE TITLE
Model for List was not found

### ISSUE THREAD

**Issue by guija** [stavshamir/springwolf#15] opened 2020-05-19 14:47 UTC
Hi. I have a KafkaListener like this:
```
@KafkaListener(topics = "topic", groupId = "groupId")
public void listen(List<Order> orders) {
	// Magic
}
```
Now if I include swagger4kafka: (Need to exclude logback and springfox-core because I'm not using logback and a more recent version of springfox 2.9.2).
```
<dependency>
    <groupId>io.github.stavshamir</groupId>
    <artifactId>swagger4kafka</artifactId>
    <version>0.0.1</version>
    <exclusions>
        <exclusion>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </exclusion>
        <exclusion>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>io.github.stavshamir</groupId>
    <artifactId>swagger4kafka-ui</artifactId>
    <version>0.0.1</version>
</dependency>
```
When starting up the spring boot application I get the following error:
`{"instant":{"epochSecond":1589899103,"nanoOfSecond":976000000},"thread":"main","level":"ERROR","loggerName":"io.github.stavshamir.swagger4kafka.services.ModelsService","message":"Model for List was not found","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":1,"threadPriority":5,"source":{"class":"io.github.stavshamir.swagger4kafka.services.ModelsService","method":"getExample","file":"ModelsService.java","line":110}}`

I can contribute on this, but I need a hint in the right direction. Does Swagger not have default models for standard types like lists or sets that could be used here?

**Comment by stavshamir** [comment] 2020-05-19 18:45
Thanks for opening the issue. I did not check for collections as payloads, which is obviously a perfectly valid use case.

I looked and the problem is related to erasure - since the payload type is `List` and not `List<Order>`, the model is not constructed properly.

Basically what happens is that through reflection, the payload of the listener method is found (in the `KafkaListenersScanner` class). Then it is passed to the `ModelsService` class that registers the model. In your case the payload is `List`, so the model is not correct.

There could be two approaches here - either to check if the payload is a collection, and then to extract the generic parameter and pass it to the `ModelService`, register it, and manually generating the example, or better - to find out how `io.swagger.converter.ModelConverters` deals with generic types and mimic it.

If you could provide a pull request it would be more then welcome! I will also look further into it because it really is a major issue.

**Comment by guija** [comment] 2020-05-19 19:50
Perfect, thanks for the hints, I think I get the idea. I will definetly look into the issue, but probably during this weekend.

**Comment by stavshamir** [comment] 2020-07-23 06:48
It looks like this will not be an easy fix. It can be easily solved in the client by using a wrapper class, for example:
```java
public class WrapperOfList {
    private List<String> list;
}
```

I might look into a better solution in the future, but I will be closing this for now.

**Closed by stavshamir** 2020-07-23 06:48 UTC
Labels: bug
